# Generated by Django 5.2.8 on 2025-11-23 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_biometricrecord_state_prediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('app', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('url', models.CharField(blank=True, max_length=1000)),
                ('active', models.BooleanField(default=False)),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.biometricrecord')),
            ],
        ),
    ]
